/**
 * `chorus quickstart` — fire a 30-second self-test review against
 * whatever CLI the user has on PATH and tail it inline.
 *
 * The activation moment. Telemetry post-launch showed 78% of installs
 * never fired a chat — the bottleneck is the gap between `chorus start`
 * (daemon comes up) and the user actually invoking an MCP tool from
 * their CLI. Six steps before they see a result. Quickstart compresses
 * that to one command:
 *
 *   1. Detect CLIs on PATH.
 *   2. Upsert a private `quickstart-self-test` template that uses ONE
 *      reviewer slot on the user's first detected lineage (no cross-
 *      lineage requirement, so it works for users who only have one CLI
 *      installed).
 *   3. POST /chats with a hardcoded sample artifact (an off-by-one
 *      bug) so the review has something concrete to discuss.
 *   4. Poll `/chats/:id` until terminal, render reviewer outputs as
 *      they arrive on disk.
 *   5. Print the run URL + a "what just happened" summary.
 *
 * Failure modes surface clearly:
 *   - No CLIs detected → point at `chorus connect` and `chorus diagnose`
 *   - Daemon not running → instruct `chorus start`
 *   - Reviewer failed (auth/quota) → show the kind+message from the
 *     `## REVIEWER FAILED` summary that runReviewer writes
 */
import type { Command } from 'commander';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import {
  isDaemonHealthy,
  readDaemonInfo,
} from '../../lib/daemon-discovery.js';
import { c, sym } from '../ui.js';

const QUICKSTART_TEMPLATE_ID = 'quickstart-self-test';

const SAMPLE_ARTIFACT = `// Quickstart self-test artifact — a tiny snippet with a real bug.
// Reviewers should flag the off-by-one in the loop bound.

function average(numbers) {
  let sum = 0;
  for (let i = 0; i <= numbers.length; i++) {
    sum += numbers[i];
  }
  return sum / numbers.length;
}
`;

const SAMPLE_WORK =
  'Quickstart self-test for chorus — does the reviewer catch the off-by-one in the average() loop?';

interface QuickstartOptions {
  daemonUrl?: string;
}

/** Build the smallest valid review-only YAML that uses one detected lineage. */
function buildQuickstartYaml(lineage: string, model?: string): string {
  // Keep crossLineage off — a user with only one CLI installed must
  // still be able to run quickstart. The 'require: 1' threshold means
  // a single reviewer's verdict is enough to settle the chat.
  return `id: ${QUICKSTART_TEMPLATE_ID}
name: Quickstart Self-Test
description: |
  Auto-generated by \`chorus quickstart\` — single reviewer slot routed
  to whichever CLI the user has on PATH. Replaced on every quickstart
  invocation to match the latest detected lineage.
author: chorus
agreementThreshold: 1.0
onThresholdMet: ask
maxRounds: 1
yoloDefault: false
estimatedBaselineTokens: 300
ship:
  enabled: false
phases:
  - id: review
    kind: review_only
    title: Quickstart Review
    description: Single reviewer critiques the supplied artifact.
    reviewer:
      require: 1
      crossLineage: false
      candidates:
        - lineage: ${lineage}${model ? `\n          models:\n            - ${model}` : ''}
    inputs:
      include: []
      exclude: []
    artifact:
      label: Code snippet
      hint: Quickstart self-test artifact (auto-supplied).
      maxBytes: 16384
`;
}

interface ChatStatus {
  id: string;
  status: string;
  verdict: string | null;
  finished_at: number | null;
}

async function pollChat(
  baseUrl: string,
  chatId: string,
  signal: AbortSignal,
): Promise<ChatStatus> {
  let lastStatus = '';
  while (!signal.aborted) {
    const r = await fetch(`${baseUrl}/chats/${chatId}`);
    if (!r.ok) throw new Error(`status fetch failed: ${r.status}`);
    const env = (await r.json()) as { data?: ChatStatus };
    const data = env.data;
    if (!data) throw new Error('chat status missing data');
    if (data.status !== lastStatus) {
      process.stdout.write(`  ${c.gray('·')} status: ${c.cyan(data.status)}\n`);
      lastStatus = data.status;
    }
    if (
      data.status === 'approved' ||
      data.status === 'merged' ||
      data.status === 'blocked' ||
      data.status === 'cancelled' ||
      data.status === 'failed' ||
      data.status === 'no_review'
    ) {
      return data;
    }
    await new Promise((resolve) => setTimeout(resolve, 1500));
  }
  throw new Error('aborted');
}

function readReviewerAnswer(chatDir: string): { kind: string; body: string } | null {
  // Round 1 is the only round for review-only; one reviewer dir lives
  // inside it (we built the template that way). Walk to find it.
  const round1 = path.join(chatDir, 'round-1');
  if (!fs.existsSync(round1)) return null;
  const reviewerDirs = fs
    .readdirSync(round1)
    .filter((n) => n.startsWith('reviewer-'));
  if (reviewerDirs.length === 0) return null;
  const answerFile = path.join(round1, reviewerDirs[0], 'answer.md');
  if (!fs.existsSync(answerFile)) return null;
  const body = fs.readFileSync(answerFile, 'utf-8');
  if (body.startsWith('## REVIEWER FAILED')) {
    return { kind: 'failed', body };
  }
  return { kind: 'ok', body };
}

export async function runQuickstart(opts: QuickstartOptions = {}): Promise<void> {
  console.log('');
  console.log(`  ${sym.rocket} ${c.bold('Chorus quickstart')} ${c.dim('— 30-second self-test')}`);
  console.log('');

  // 1. Daemon up?
  const info = readDaemonInfo();
  if (!info) {
    console.log(`  ${c.red('✗')} daemon not running`);
    console.log(`     run ${c.bold('chorus start')} first, then re-run quickstart`);
    process.exitCode = 1;
    return;
  }
  const healthy = await isDaemonHealthy(info.daemonPort, 1500);
  if (!healthy) {
    console.log(`  ${c.red('✗')} daemon not responding on :${info.daemonPort}`);
    console.log(`     run ${c.bold('chorus stop && chorus start')} to recycle`);
    process.exitCode = 1;
    return;
  }
  const baseUrl = opts.daemonUrl ?? `http://127.0.0.1:${info.daemonPort}`;
  console.log(`  ${c.green('✓')} daemon healthy on :${info.daemonPort}`);

  // 2. Pick a CLI lineage.
  const { detectAllClis } = await import('../../lib/cli-detect.js');
  // Map cli-detect ids to lineage strings the template-schema accepts.
  // Models intentionally omitted — the daemon's voices seed picks the
  // canonical default for each lineage, which keeps quickstart in sync
  // with whatever the user has configured / whatever ships as the
  // current default. Hardcoding model strings here proved brittle in
  // self-review (4 reviewers flagged drift risk for kimi-k2.6, gpt-5.5,
  // opencode/claude-sonnet-4-6).
  //
  // grok-cli is included now that we have a shim. It still needs a
  // SuperGrok Heavy subscription at dispatch time — quickstart's
  // single-reviewer slot will surface a quota_exhausted error cleanly
  // if the user is on a free tier. That's preferable to silently
  // skipping the only detected CLI.
  const cliToLineage: Record<string, string> = {
    'claude-code': 'anthropic',
    'codex-cli': 'openai',
    'gemini-cli': 'google',
    'opencode-cli': 'opencode',
    'kimi-cli': 'moonshot',
    'grok-cli': 'grok',
  };
  const detected = detectAllClis(true)
    .filter((d) => d.found)
    .filter((d) => cliToLineage[d.id] !== undefined);
  if (detected.length === 0) {
    console.log('');
    console.log(`  ${c.red('✗')} no dispatchable CLIs detected on PATH`);
    console.log(
      `     install Claude Code, Codex, Gemini CLI, OpenCode, or Kimi CLI`,
    );
    console.log(`     then run ${c.bold('chorus connect')} to wire MCP`);
    console.log(`     ${c.gray('details:')} ${c.bold('chorus diagnose')}`);
    process.exitCode = 1;
    return;
  }
  const first = detected[0];
  const lineage = cliToLineage[first.id];
  if (!lineage) {
    // Unreachable — filter above guarantees lineage exists.
    console.log(`  ${c.red('✗')} detected CLI '${first.id}' has no quickstart mapping`);
    process.exitCode = 1;
    return;
  }
  console.log(
    `  ${c.green('✓')} reviewer: ${c.bold(first.id)} ${c.gray('(lineage:')} ${lineage}${c.gray(')')}`,
  );

  // 3. Upsert the quickstart template (no model — defaults from the seed).
  const yaml = buildQuickstartYaml(lineage);
  const upsert = await fetch(`${baseUrl}/templates`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ id: QUICKSTART_TEMPLATE_ID, yaml }),
  });
  if (!upsert.ok) {
    const text = await upsert.text();
    console.log(`  ${c.red('✗')} template upsert failed: ${upsert.status} ${text.slice(0, 200)}`);
    process.exitCode = 1;
    return;
  }
  console.log(`  ${c.green('✓')} template seeded`);

  // 4. Fire the chat.
  const chatRes = await fetch(`${baseUrl}/chats`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      work: SAMPLE_WORK,
      templateId: QUICKSTART_TEMPLATE_ID,
      artifact: SAMPLE_ARTIFACT,
    }),
  });
  if (!chatRes.ok) {
    const text = await chatRes.text();
    console.log(`  ${c.red('✗')} chat create failed: ${chatRes.status} ${text.slice(0, 200)}`);
    process.exitCode = 1;
    return;
  }
  const chatEnv = (await chatRes.json()) as { data?: { id: string } };
  const chatId = chatEnv.data?.id;
  if (!chatId) {
    console.log(`  ${c.red('✗')} chat create returned no id`);
    process.exitCode = 1;
    return;
  }
  const cockpitUrl = await resolveCockpitUrlSafe();
  console.log(`  ${c.green('✓')} chat fired ${c.gray('(id: ' + chatId + ')')}`);
  if (cockpitUrl) {
    console.log(`     watch live: ${c.cyan(`${cockpitUrl}/runs/${chatId}`)}`);
  }
  console.log('');

  // 5. Poll until terminal. Cap at 4 minutes — if a reviewer hasn't
  // finished by then, something's wrong with the CLI itself, not chorus.
  // Ctrl+C handler is registered BEFORE polling so a user who bails
  // mid-chat doesn't leave the daemon running an orphan reviewer in
  // the background. Self-review (4 reviewers) flagged this as the
  // primary blocker — without cancel-on-SIGINT, every quickstart that
  // gets interrupted leaves a chat consuming subscription quota.
  const ac = new AbortController();
  const timeout = setTimeout(() => ac.abort(), 4 * 60_000);
  let cancelled = false;
  const onSigint = (): void => {
    if (cancelled) return;
    cancelled = true;
    ac.abort();
    // Best-effort daemon cancel. Synchronous-ish — we don't await
    // because the SIGINT handler should return quickly so Node can
    // exit cleanly. The daemon's /chats/:id/cancel route is idempotent
    // so a double-cancel is harmless.
    void fetch(`${baseUrl}/chats/${chatId}/cancel`, { method: 'POST' }).catch(() => {
      /* daemon may already be tearing down — best effort */
    });
    console.log('');
    console.log(`  ${c.gray('Ctrl-C — cancelling chat ' + chatId + '...')}`);
  };
  process.on('SIGINT', onSigint);
  let final: ChatStatus;
  try {
    final = await pollChat(baseUrl, chatId, ac.signal);
  } catch (err) {
    console.log(`  ${c.red('✗')} ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
    return;
  } finally {
    clearTimeout(timeout);
    process.off('SIGINT', onSigint);
  }

  console.log('');
  console.log(`  ${sym.pointer} ${c.bold('Result')} ${c.gray('— status: ' + final.status + (final.verdict ? ', verdict: ' + final.verdict : ''))}`);
  console.log('');

  // 6. Render the reviewer's output (or its failure summary).
  const chatDir = path.join(os.homedir(), '.chorus', 'chats', chatId);
  const answer = readReviewerAnswer(chatDir);
  if (!answer) {
    console.log(`  ${c.gray('(no reviewer output on disk yet — refresh the run page)')}`);
  } else if (answer.kind === 'failed') {
    console.log(c.red(answer.body.slice(0, 1500)));
    console.log('');
    console.log(`  ${c.gray('see')} ${c.bold('chorus diagnose')} ${c.gray('for failure context')}`);
    process.exitCode = 1;
    return;
  } else {
    // Trim long responses to ~80 lines so terminal isn't flooded.
    const lines = answer.body.split('\n');
    const display = lines.slice(0, 80).join('\n');
    console.log(display);
    if (lines.length > 80) {
      console.log(`  ${c.gray(`(${lines.length - 80} more lines on disk)`)}`);
    }
  }
  console.log('');
  if (cockpitUrl) {
    console.log(`  ${c.gray('full run:')} ${c.cyan(`${cockpitUrl}/runs/${chatId}`)}`);
  }
  console.log('');
}

async function resolveCockpitUrlSafe(): Promise<string | null> {
  // Read the cockpit port out of `~/.chorus/daemon.json` rather than
  // string-substituting the daemon URL (the substitution broke on any
  // non-default port — `:17707` → `:15050`, and any user with a
  // custom cockpit port saw a wrong link). The daemon writes both
  // ports to daemon.json on startup; falling back to null means the
  // terminal output simply omits the link rather than printing one
  // that 404s.
  try {
    const info = readDaemonInfo();
    if (!info) return null;
    return `http://127.0.0.1:${info.cockpitPort}`;
  } catch {
    return null;
  }
}

export function registerQuickstartCommand(program: Command): void {
  program
    .command('quickstart')
    .description(
      'Fire a 30-second sample chat against your first-detected CLI to confirm chorus works end-to-end',
    )
    .action(async () => {
      try {
        await runQuickstart();
      } catch (err) {
        console.error('quickstart failed:', err instanceof Error ? err.message : err);
        process.exit(1);
      }
    });
}

export const _testing = {
  buildQuickstartYaml,
  QUICKSTART_TEMPLATE_ID,
  SAMPLE_ARTIFACT,
  SAMPLE_WORK,
};
